import AI_Powered_Quiz_Cover_Image from "src/assets/images/Apps/AI_Powered_Quiz/AI Powered Quiz.png";
import custom_lMS_mvp_app_cover_image from "src/assets/images/Apps/custom-lMS-mvp-app/Custom LMS MVP.png";
import TutorAICoverImage from "src/assets/images/Apps/Tutor_AI/Tutor_AI_CoverImage.png";
import Tutor_LMS_Cover_Image from "src/assets/images/Apps/Tutor_LMS/Tutor LMS.png";

export const Application_Images = [
  {
    id: 1,
    src: "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761114691/2_aozzi5.png",
  },
  {
    id: 2,
    src: "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761114691/3_aimvhr.png",
  },
  {
    id: 3,
    src: "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761114691/1_s9fzp3.png",
  },
  {
    id: 4,
    src: "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761114691/4_fo4qa7.png",
  },
  {
    id: 5,
    src: "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761114691/5_rgpjeu.png",
  },
  {
    id: 6,
    src: "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761114691/6_pylvtv.png",
  },
];

export const About = {
  headerText: "Revolutionary Learning Experience with AI Adaptive Learning",
  description: [
    `Discover how our AI-powered platform transforms education — making learning more personalized, intelligent, and results-driven.`,
  ],
  points: [
    "AI-driven personalized learning experiences for every student",
    "Role-based dashboards for Students, Teachers, Parents, and Administrators",
    "Adaptive assignments and quizzes generated by AI",
    "Real-time progress tracking and performance analytics",
    "Interactive AI Tutor with multi-level contextual guidance",
    "Secure authentication and Row-Level Security (RLS) via Supabase",
    "Lesson and assignment management tools for teachers",
    "Parent portal for monitoring child progress and activities",
    "Administrator control panel for user and system management",
    "Modern, responsive UI built with React, TypeScript, and Tailwind CSS",
  ],
  // imageSrc: Interactive_Learning_image,
  // imageAlt: "Why Schools Choose Atlearn?",
  // linkText: "Join a Meeting",
  // linkHref: "/join-meetings",
};

export const AI_Adaptive_Learning_CTA = {
  // label: "Transform Learning, Simplify Teaching",
  heading: "AI Adaptive Learning — Built to Evolve with Every Student",
  description:
    "Empower your institution with personalized, data-driven education. Our AI analyzes student performance in real time, adapting lessons and assessments to ensure every learner achieves their best.",
  // ctaName: "Claim Your LMS",
  // embedPopupFormId: "mbambgcjdr6kv0zhhvt",
};

export const moreApps = [
  {
    id: 1,
    src: AI_Powered_Quiz_Cover_Image,
    title: "AI Quiz Platform",
    link: "/ai-powered-quiz-app",
  },
  {
    id: 2,
    src: custom_lMS_mvp_app_cover_image,
    title: "Custom LMS Platform",
    link: "/custom-lMS-mvp-app",
  },
  {
    id: 3,
    src: TutorAICoverImage,
    title: "Tutor AI ",
    link: "/tutor-ai-app",
  },
  {
    id: 4,
    src: Tutor_LMS_Cover_Image,
    title: "Tutor LMS Application",
    link: "/tutor-web-app",
  },
];

export const AI_Adaptive_Learning_bottom_CTA = {
  // label: "Transform Learning, Simplify Teaching",
  heading: "Empower Learning with Your Own AI-Powered Platform",
  description:
    "Deliver personalized education experiences with adaptive lessons, progress tracking, and AI-driven insights. We’ll customize this platform for your organization — making smart learning simple, scalable, and effective.",
  ctaName: "Book a Demo Session",
  embedPopupFormId: "mbambgcjdr6kv0zhhvt",
};

export const coreFeatures = [
  {
    title: "Student",
    description:
      "Personalized dashboard, assignments, progress tracking, and AI Tutor support",
    image:
      "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761115242/student--icon---nice-modern-style-_jwrq1h.svg",
  },
  {
    title: "Teacher",
    description:
      "Lesson creation, assignment management, analytics, and tutor monitoring",
    image:
      "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761115242/teacher-icon---nice-modern-style-_nzrlec.svg",
  },
  {
    description:
      "Child performance tracking, activity overview, and multi-child support",
    title: "Parent",
    image:
      "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761115242/parent-icon---nice-modern-style-_uwqmub.svg",
  },
  {
    image:
      "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761115242/administrator-icon---nice-modern-style-_i22a5v.svg",
    title: "Administrator",
    description: "User management, system analytics, and platform monitoring",
  },
  {
    description:
      "Context-aware learning assistance with multi-level hints and chat history",
    title: "AI Tutor",
    image:
      "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761115241/ai-tutor-icon---nice-modern-style-_hipwdh.svg",
  },
  {
    title: "Adaptive Assessment",
    image:
      "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761115241/adaptive-assestment-icon---nice-modern-style-_kprbuv.svg",
    description:
      "AI-generated quizzes, automatic grading, and learning style detection",
  },
  {
    description:
      "Lesson content management, adaptive task generation, and submissions",
    title: "Lesson & Assignment",
    image:
      "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761115240/lesson-and-assigment-icon---nice-modern-style-_pgsoif.svg",
  },
  {
    description:
      "Performance metrics, visual reports, and comprehension insights",
    title: "Progress & Analytics",
    image:
      "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761115240/progress-and-analytics--icon---modern-style_yf2tsc.svg",
  },
  {
    title: "Authentication & Access Control",
    image:
      "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761115241/authentication-and-access-control-icon---modern-st_ajloxx.svg",
    description: "Role-based login, routing, and secure RLS enforcement",
  },
  {
    title: "Database & AI Integration",
    image:
      "https://res.cloudinary.com/dpz1aa6ff/image/upload/v1761115240/database-and-integration-icon---modern-style_luzfaj.svg",
    description: "Supabase backend with Lovable AI-powered Edge Functions",
  },
];

export const frd = `
# AI Adaptive Learning Platform  \n**Functional Specification Document**\n\n---\n\n## 1. Executive Summary  \nThe AI Adaptive Learning Platform is a comprehensive educational system that leverages artificial intelligence to provide personalized learning experiences.  \nThe platform supports four distinct user roles: Students, Teachers, Parents, and Administrators, each with role-specific features and dashboards.\n\n---\n\n## 2. System Overview  \n\n### 2.1 Core Purpose  \n- Deliver adaptive learning experiences tailored to individual student needs  \n- Enable teachers to create and manage lessons and assignments  \n- Provide parents with visibility into their children's progress  \n- Give administrators tools to manage users and monitor platform analytics  \n\n### 2.2 Technology Stack  \n- **Frontend:** React, TypeScript, Vite, Tailwind CSS  \n- **Backend:** Supabase (PostgreSQL database, Edge Functions)  \n- **Authentication:** Supabase Auth  \n- **AI Integration:** Lovable AI API for adaptive content generation  \n\n---\n\n## 3. User Roles & Access Control  \n\n### 3.1 Role Hierarchy  \n- Administrator - Full system access  \n- Teacher - Lesson and assignment management  \n- Parent - Child progress monitoring  \n- Student - Learning activities and assignments  \n\n### 3.2 Security Model  \n- Row-Level Security (RLS) policies on all database tables  \n- Role-based access control using user_roles table  \n- Secure authentication via Supabase Auth  \n- Security definer functions for role checking  \n\n---\n\n## 4. Student Portal  \n\n### 4.1 Dashboard  \n- **Route:** /student  \n- Features:  \n  - Overview of active assignments  \n  - Progress tracking metrics  \n  - Quick access to recent lessons  \n  - Performance summary cards  \n  - Upcoming deadlines  \n\n### 4.2 Assignments  \n- **Route:** /student/assignments  \n- Features:  \n  - View all assigned tasks  \n  - Filter by status (Not Started, In Progress, Completed)  \n  - Access assignment details and instructions  \n  - Submit completed work  \n  - View feedback and grades  \n- Assignment Structure:  \n  - Title and description  \n  - Instructions and expected outcomes  \n  - Activity steps (JSON-based structure)  \n  - Submission tracking  \n  - Status management  \n\n### 4.3 Assignment Detail View  \n- **Route:** /student/assignments/:id  \n- Features:  \n  - Detailed assignment instructions  \n  - Step-by-step activity guide  \n  - Progress tracking within assignment  \n  - Submission interface  \n  - AI Tutor integration for help  \n\n### 4.4 AI Tutor  \n- **Route:** /student/ai-tutor  \n- Features:  \n  - Conversational AI interface  \n  - Context-aware hints based on current assignment  \n  - Multiple hint levels (subtle, moderate, detailed)  \n  - Chat history preservation  \n  - Real-time assistance  \n- AI Tutor Functionality:  \n  - Hint Level 1: Subtle prompts and questions  \n  - Hint Level 2: Moderate guidance with examples  \n  - Hint Level 3: Detailed explanations and step-by-step help  \n  - Session tracking for teacher review  \n\n### 4.5 Progress Tracking  \n- **Route:** /student/progress  \n- Features:  \n  - Overall performance metrics  \n  - Subject-wise progress breakdown  \n  - Assignment completion rates  \n  - Strengths and areas for improvement  \n  - Visual charts and graphs  \n\n### 4.6 Diagnostic Quizzes  \n- Features:  \n  - AI-generated quizzes based on lesson content  \n  - Multiple question types (multiple choice, etc.)  \n  - Automatic scoring and feedback  \n  - Comprehension tier assessment  \n  - Learning style identification  \n- Assessment Outcomes:  \n  - Comprehension Tier: Basic, Intermediate, Advanced  \n  - Learning Style: Visual, Auditory, Kinesthetic, Reading/Writing  \n  - Behavioral signals tracking  \n  - Cognitive signals analysis  \n\n---\n\n## 5. Teacher Portal  \n\n### 5.1 Dashboard  \n- **Route:** /teacher  \n- Features:  \n  - Overview of all lessons  \n  - Recent assignment submissions  \n  - Student performance summary  \n  - Quick stats and analytics  \n  - Class management overview  \n\n### 5.2 Lessons Management  \n- **Route:** /teacher/lessons  \n- Features:  \n  - Create new lessons  \n  - Edit existing lessons  \n  - Upload lesson materials  \n  - Organize by subject and grade level  \n  - Lesson content editor  \n- Lesson Structure:  \n  - Title and description  \n  - Subject and grade level  \n  - Detailed content/curriculum  \n  - File attachments (optional)  \n  - Teacher ownership tracking  \n\n### 5.3 Assignments Management  \n- **Route:** /teacher/assignments  \n- Features:  \n  - Create assignments from lessons  \n  - Assign to specific students  \n  - Set instructions and expected outcomes  \n  - Define activity steps  \n  - Monitor submission status  \n- Assignment Creation:  \n  - Link to lesson content  \n  - Customizable instructions  \n  - Expected outcomes definition  \n  - Activity step configuration (JSON-based)  \n  - Adaptive task generation via AI  \n\n### 5.4 Analytics Dashboard  \n- **Route:** /teacher/analytics  \n- Features:  \n  - Student performance metrics  \n  - Assignment completion rates  \n  - Average scores and grades  \n  - Time spent on assignments  \n  - Engagement analytics  \n  - Comprehension tier distribution  \n  - Learning style breakdown  \n\n### 5.5 Tutor Monitor  \n- **Route:** /teacher/tutor-monitor  \n- Features:  \n  - View all AI tutor sessions  \n  - Monitor student questions  \n  - Track hint usage  \n  - Identify struggling students  \n  - Review resolution status  \n  - Session timestamps and details  \n- Monitoring Capabilities:  \n  - Real-time session tracking  \n  - Hint count per student  \n  - Question context review  \n  - Intervention triggers  \n\n### 5.6 Overview  \n- **Route:** /teacher/overview  \n- Features:  \n  - Comprehensive class statistics  \n  - Recent activity feed  \n  - Student progress summaries  \n  - Quick action buttons  \n  - Pending review alerts  \n\n---\n\n## 6. Parent Portal  \n\n### 6.1 Dashboard  \n- **Route:** /parent  \n- Features:  \n  - Children's overview  \n  - Recent activity summary  \n  - Performance highlights  \n  - Upcoming assignments  \n  - Alert notifications  \n\n### 6.2 Progress Monitoring  \n- **Route:** /parent/progress  \n- Features:  \n  - Detailed child performance metrics  \n  - Subject-wise progress  \n  - Strengths and weaknesses analysis  \n  - Historical performance trends  \n  - Comparison with class average  \n\n### 6.3 Assignments View  \n- **Route:** /parent/assignments  \n- Features:  \n  - View all child's assignments  \n  - Assignment status tracking  \n  - Due date monitoring  \n  - Completed work review  \n  - Teacher feedback access  \n\n### 6.4 Multi-Child Support  \n- Features:  \n  - Link multiple children to parent account  \n  - Switch between children's profiles  \n  - Consolidated reporting  \n  - Individual child tracking  \n- Database Support:  \n  - student_children table for relationships  \n  - Parent-child linkage via parent_id and student_id  \n  - Relationship type tracking  \n\n---\n\n## 7. Administrator Portal  \n\n### 7.1 Dashboard  \n- **Route:** /admin  \n- Features:  \n  - System-wide statistics  \n  - User management overview  \n  - Platform health metrics  \n  - Recent activity logs  \n  - Quick access to all admin functions  \n\n### 7.2 User Management  \n- **Route:** /admin/users  \n- Features:  \n  - View all platform users  \n  - User details (name, email, roles)  \n  - Role assignment and modification  \n  - User creation and deletion  \n  - Real-time user updates  \n  - Search and filter capabilities  \n- User Management Capabilities:  \n  - Create new users with roles  \n  - Assign multiple roles to users  \n  - Modify existing user roles  \n  - View user profile information  \n  - Track user creation dates  \n\n### 7.3 Analytics  \n- **Route:** /admin/analytics  \n- Features:  \n  - Platform-wide usage statistics  \n  - User engagement metrics  \n  - Feature utilization reports  \n  - Performance analytics  \n  - System health monitoring  \n\n### 7.4 Overview  \n- **Route:** /admin/overview  \n- Features:  \n  - Comprehensive system dashboard  \n  - Key performance indicators  \n  - User distribution by role  \n  - Active sessions monitoring  \n  - System alerts and notifications  \n\n---\n\n## 8. Authentication System  \n\n### 8.1 User Registration  \n- **Route:** /auth (Sign Up tab)  \n- Features:  \n  - Email/password registration  \n  - User metadata collection (full name, grade level)  \n  - Role selection during signup  \n  - Automatic profile creation  \n  - Email verification (optional)  \n- Registration Flow:  \n  - User provides email, password, full name  \n  - Optional: Grade level for students  \n  - Role assignment (student by default)  \n  - Trigger creates profile in profiles table  \n  - Role inserted in user_roles table  \n\n### 8.2 User Login  \n- **Route:** /auth (Sign In tab)  \n- Features:  \n  - Email/password authentication  \n  - Session management  \n  - Automatic role detection  \n  - Role-based dashboard routing  \n  - \"Remember me\" functionality  \n\n### 8.3 Role-Based Routing  \n- Functionality:  \n  - After login, redirect based on primary role  \n  - Priority order: Teacher > Admin > Parent > Student  \n  - Protected routes with AuthGuard  \n  - Automatic session persistence  \n  - Logout functionality across all portals  \n\n---\n\n## 9. AI-Powered Features  \n\n### 9.1 AI Tutor System  \n- **Edge Function:** ai-tutor  \n- Capabilities:  \n  - Context-aware hint generation  \n  - Adaptive hint levels  \n  - Chat history maintenance  \n  - Question analysis  \n  - Natural language interaction  \n- Implementation:  \n  - Supabase Edge Function  \n  - Integration with Lovable AI API  \n  - Session logging in tutor_sessions table  \n  - Real-time response generation  \n\n### 9.2 Adaptive Task Generation  \n- **Edge Function:** generate-adaptive-tasks  \n- Capabilities:  \n  - Lesson-based task creation  \n  - Comprehension tier adaptation (Basic, Intermediate, Advanced)  \n  - Learning style customization (Visual, Auditory, Kinesthetic, Reading/Writing)  \n  - Structured task output  \n  - Activity step generation  \n- Process Flow:  \n  - Teacher creates lesson  \n  - System fetches lesson content  \n  - AI analyzes content and student profile  \n  - Generates tier-appropriate tasks  \n  - Returns structured assignment data  \n\n### 9.3 Diagnostic Quiz Generation  \n- **Edge Function:** generate-quiz  \n- Capabilities:  \n  - Automatic quiz creation from lesson content  \n  - Multiple question types  \n  - Difficulty level balancing  \n  - Point allocation  \n  - Question ordering  \n- Quiz Structure:  \n  - Quiz metadata (title, instructions)  \n  - Multiple questions with options  \n  - Correct answer tracking  \n  - Point values per question  \n  - Question order management  \n\n---\n\n## 10. Database Schema  \n\n### 10.1 Core Tables  \n- **profiles:** Stores user profile information (id, email, full_name, grade_level, school_id). Links to auth.users. Automatically created on user signup.  \n- **user_roles:** Manages role assignments (id, user_id, role). Supports multiple roles per user. Security definer function for role checking.  \n- **lessons:** Teacher-created lesson content (id, teacher_id, title, description, content, subject, grade_level, file_url). Owned by teachers. Accessible to students.  \n- **quizzes:** Diagnostic assessments (id, lesson_id, title, instructions). Linked to lessons. Container for quiz questions.  \n- **quiz_questions:** Individual quiz questions (id, quiz_id, question_text, question_type, options (JSON), correct_answer, points, order_index). Supports multiple question types. Structured JSON for options.  \n- **quiz_attempts:** Student quiz submissions (id, quiz_id, student_id, answers (JSON), score, time_spent, comprehension_tier, learning_style, behavioral_signals, cognitive_signals). Tracks assessment outcomes. Feeds adaptive learning system.  \n- **assignments:** Student work assignments (id, lesson_id, student_id, title, instructions, expected_outcomes, activity_steps (JSON), strategy_used, status, quiz_attempt_id, submitted_at). Links to lessons and quiz attempts. Tracks completion status.  \n- **tutor_sessions:** AI tutor interactions (id, student_id, assignment_id, question, hints_given, hint_count, resolved). Enables teacher monitoring. Tracks help requests.  \n- **student_children:** Parent-child relationships (id, parent_id, student_id, relationship). Enables multi-child support. Parent portal access control.  \n\n### 10.2 Custom Types (Enums)  \n- **app_role:** Values: admin, teacher, student, parent. Used in user_roles table.  \n- **comprehension_tier:** Values: basic, intermediate, advanced. Tracks student understanding level.  \n- **learning_style:** Values: visual, auditory, kinesthetic, reading_writing. Personalizes content delivery.  \n\n---\n\n## 11. Security Model  \n\n### 11.1 Row-Level Security Policies  \n- **Profiles:** Users can view/update own profile. Parents can view children's profiles. Users can insert own profile on signup.  \n- **User Roles:** Users can view own roles. Admins can manage all roles. Users can insert first role on signup.  \n- **Lessons:** Teachers can create/manage own lessons. Students can view all lessons. Admins can view all lessons.  \n- **Assignments:** Students can view/update own assignments. Teachers can view assignments for their lessons. Admins can view all assignments.  \n- **Quizzes & Questions:** Teachers can manage quizzes for their lessons. Students can view quizzes.  \n- **Quiz Attempts:** Students can create/view own attempts. Teachers can view attempts for their lessons. Admins can view all attempts.  \n- **Tutor Sessions:** Students can manage own sessions. Teachers can view sessions for their assignments.  \n- **Student Children:** Parents can manage their children relationships.  \n\n### 11.2 Database Functions  \n- **has_role(user_id, role):** Security definer function. Checks if user has specific role. Prevents RLS recursion. Used in all role-based policies.  \n- **handle_new_user():** Trigger function on user creation. Creates profile entry. Assigns default role. Extracts metadata from signup.  \n- **update_updated_at_column():** Trigger function for timestamp updates. Updates updated_at on record modification.  \n\n---\n\n## 12. User Interface Components  \n\n### 12.1 Common Components  \n- **Layouts:**  \n  - StudentLayout: Sidebar navigation, header with profile  \n  - TeacherLayout: Sidebar navigation, header with profile  \n  - ParentLayout: Sidebar navigation, header with profile  \n  - AdminLayout: Sidebar navigation, header with profile  \n- **UI Elements:**  \n  - Avatar with user initials  \n  - Notification bell with indicator  \n  - Dropdown menu for profile actions  \n  - Sidebar with collapsible navigation  \n  - Responsive design for mobile/tablet/desktop  \n\n### 12.2 Design System  \n- **Color Scheme:** Semantic tokens from index.css, HSL color format, Theme-aware components, Gradient support for branding  \n- **Components Library:** Shadcn/UI components, Radix UI primitives, Custom styled components, Consistent design patterns  \n\n---\n\n## 13. Technical Specifications  \n\n### 13.1 Frontend Architecture  \n- React 18 with TypeScript  \n- React Router for navigation  \n- TanStack Query for data fetching  \n- Tailwind CSS for styling  \n- Vite for build tooling  \n\n### 13.2 Backend Architecture  \n- Supabase PostgreSQL database  \n- Edge Functions (Deno runtime)  \n- RESTful API via Supabase client  \n- Real-time subscriptions  \n\n### 13.3 External Integrations  \n- Lovable AI API for AI features  \n- Supabase Auth for authentication  \n- Supabase Storage (configured for future use)  \n\n### 13.4 Real-Time Features  \n- User list updates in Admin portal  \n- Assignment status updates  \n- Live tutor session monitoring  \n- Notification system  \n\n---\n\n## 14. Future Enhancements & Considerations  \n\n### 14.1 Potential Additions  \n- File upload for assignments  \n- Direct messaging between users  \n- Calendar integration  \n- Mobile app version  \n- Gamification elements  \n- Certificate generation  \n- Export reports to PDF  \n- Integration with third-party LMS  \n\n### 14.2 Scalability Considerations  \n- Database indexing optimization  \n- Caching strategy  \n- CDN for static assets  \n- Load balancing for Edge Functions  \n- Database connection pooling  \n\n---\n\n## 15. Deployment & Operations  \n\n### 15.1 Deployment  \n- Frontend hosted on Lovable platform  \n- Database and Edge Functions on Supabase  \n- Environment variables for API keys  \n- Automatic deployments on code changes  \n\n### 15.2 Monitoring  \n- Edge Function logs via Supabase Dashboard  \n- Client-side error tracking  \n- Performance monitoring  \n- User analytics  \n\n---\n\n**Document Version:** 1.0  \n**Date:** 2025-10-18  \n**Platform:** AI Adaptive Learning Platform  \n\n    \n
`;
